In [1]:
import pandas as pd
import numpy as np

# Problem 1: Book Recommendations

The [Book-Crossings dataset](http://www2.informatik.uni-freiburg.de/~cziegler/BX/) is a book ratings dataset compiled by Cai-Nicolas Ziegler from the [Book-Crossing community](https://www.bookcrossing.com). 
It contains 1.1 million ratings of 270,000 books by 90,000 users. 
The ratings are on a scale from 1 to 10.

Click [here](http://www2.informatik.uni-freiburg.de/~cziegler/BX/BX-CSV-Dump.zip) to download the dataset.
The data consists of three files: ratings (BX-Book-Ratings.csv), books info (BX-Books.csv), and users info (BX-Users.csv)

**Ratings data**

The ratings data set provides a list of ratings that users have given to books. It includes 1,149,780 records and 3 fields: userID, ISBN, and bookRating.

In [2]:
# load the data (you may need to change the path to the file)
path = 'BX-Book-Ratings.csv'
ratings = pd.read_csv(path, sep=';',error_bad_lines=False, encoding="latin-1")
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

**Books data**

The books data set provides book details. It includes 271,360 records and 8 fields: ISBN, book title, book author, publisher and so on.

In [3]:
path = 'BX-Books.csv'
books = pd.read_csv(path, sep=';', error_bad_lines=False, encoding="latin-1")
books

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
/Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

**Users data**

This dataset provides the user demographic information.
It includes 278,858 records and 3 fields: user id, location and age.

In [4]:
path = 'BX-Users.csv'
users = pd.read_csv(path, sep=';',  error_bad_lines=False, encoding="latin-1")
users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

## Part 1

Find the number of ratings each book received (pandas built-in function [value_counts](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html) may be useful here).

In [5]:
rate_count = ratings['ISBN'].value_counts()
rate_count

0971880107    2502
0316666343    1295
0385504209     883
0060928336     732
0312195516     723
              ...
1565650549       1
030768122X       1
808539572X       1
3426007932       1
0373160100       1
Name: ISBN, Length: 340556, dtype: int64

## Part 2

To ensure statistical significance, drop books with less than 100 ratings (pandas built-in functions [index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.index.html) and [isin](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html) may be useful here)

In [6]:
good_isbn = rate_count[rate_count >= 100].index
good_isbn

Index(['0971880107', '0316666343', '0385504209', '0060928336', '0312195516',
       '044023722X', '0679781587', '0142001740', '067976402X', '0671027360',
       ...
       '0425189864', '0140092323', '0385424736', '0786866586', '0425136981',
       '0060916508', '0449203794', '0425151867', '067100042X', '0312966806'],
      dtype='object', length=731)

In [7]:
good_ratings = ratings[ratings['ISBN'].isin(good_isbn)]
good_ratings['ISBN'].value_counts()

0971880107    2502
0316666343    1295
0385504209     883
0060928336     732
0312195516     723
              ...
0425189864     100
0060916508     100
067100042X     100
0385424736     100
0140092323     100
Name: ISBN, Length: 731, dtype: int64

In [8]:
good_books = books[books['ISBN'].isin(good_isbn)]
good_books['ISBN']

18       0440234743
19       0452264464
26       0971880107
27       0345402871
28       0345417623
            ...
28071    0425178765
29214    0449223604
30534    0345444884
30774    0060008032
35704    0515135739
Name: ISBN, Length: 727, dtype: object

It is worrying to me that these objects have different lengths.

## Part 3

Choose a book you like (from the *ratings* data), and find its ISBN number

I like The Talisman (but I've never read Black House).

In [9]:
good_books[good_books['Book-Title']=='The Talisman']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
30534,0345444884,The Talisman,STEPHEN KING,2001,Ballantine Books,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...

In [10]:
my_ISBN = good_books[good_books['Book-Title']=='The Talisman']['ISBN']
my_ISBN.values

array(['0345444884'], dtype=object)

In [15]:
book = my_ISBN.values[0]
book

'0345444884'

## Part 4

Use

- (a) Jaccard similarity $$ J(A,B) = \frac{|A\cap B|}{|A\cup B|} $$ 
- (b) serendipity similarity $$S(A,B) = \frac{|A\cap B|}{|B|}$$
- (c) overlap similarity $$O(A,B) = \frac{|A\cap B|}{\min\{|A|,|B|\}}$$
- (d) correlation similarity, and
- (e) cosine similarity

to find the top-10 book recomendations

In [12]:
book_sets = good_ratings.groupby('ISBN')['User-ID'].apply(set)

book_sets

ISBN
002542730X    {243720, 155147, 175117, 238607, 179733, 17051...
0060008032    {254465, 72707, 151043, 74758, 52248, 109620, ...
0060096195    {228868, 155141, 142861, 154137, 278554, 25142...
006016848X    {243200, 262151, 269835, 174092, 270352, 35857...
0060173289    {178181, 124942, 15890, 170518, 1559, 126492, ...
                                    ...
1573227331    {163329, 87555, 96771, 78855, 199178, 66574, 3...
1573229326    {89602, 87555, 93698, 117251, 235011, 237575, ...
1573229571    {68608, 21014, 243236, 103467, 261682, 261684,...
1592400876    {81924, 176656, 217106, 23571, 35859, 203799, ...
1878424319    {141840, 49170, 187410, 21014, 85526, 115224, ...
Name: User-ID, Length: 731, dtype: object

In [13]:
# the ratings matrix
ratings_matrix = good_ratings.pivot('User-ID','ISBN')['Book-Rating']
ratings_matrix

ISBN,002542730X,0060008032,0060096195,006016848X,0060173289,0060175400,006019491X,0060199652,0060391626,0060392452,...,1558744630,1558745157,1559029838,1573225517,1573225789,1573227331,1573229326,1573229571,1592400876,1878424319
User-ID,,,,,,,,,,,,,,,,,,,,,
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278843,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
def Jaccard_sim(set_B):
    set_A = book_sets[book]
    return len(set_A.intersection(set_B))/len(set_A.union(set_B))

def Serendipity_sim(set_B):
    set_A = book_sets[book]
    return len(set_A.intersection(set_B))/len(set_B)

def Overlap_sim(set_B):
    set_A = book_sets[book]
    return len(set_A.intersection(set_B))/np.min([len(set_A),len(set_B)])


def cosine_sim(col_B):
    col_A = ratings_matrix.loc[:,book]
    # similarity between col_A and col_B
    norm_A = np.sqrt(np.sum(col_A**2))
    norm_B = np.sqrt(np.sum(col_B**2))
    return np.sum(col_A*col_B)/(norm_A*norm_B)

def correlation_sim(col_B):
    col_A = ratings_matrix.loc[:,book]
    
    # means
    mean_A = np.mean(col_A)
    mean_B = np.mean(col_B)
    # norms
    norm_A = np.sqrt(np.sum((col_A-mean_A)**2))
    norm_B = np.sqrt(np.sum((col_B-mean_B)**2))
    # dot product
    dot = np.sum((col_A-mean_A)*(col_B-mean_B))
    return dot/(norm_A*norm_B)

## Jaccard Similarity

In [18]:
top_ten = book_sets.apply(Jaccard_sim).sort_values(ascending=False).head(10)
top_ten

ISBN
0345444884    1.000000
0451184963    0.069853
0451188462    0.068063
0451180232    0.067010
0345441036    0.066327
0743457358    0.062201
0451186362    0.059633
0451160525    0.059072
0425147517    0.055838
0671024248    0.052239
Name: User-ID, dtype: float64

In [27]:
Jaccard_ten = good_books[good_books['ISBN'].isin(top_ten.index)]
Jaccard_ten

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1926,0743457358,Everything's Eventual : 14 Dark Tales,Stephen King,2002,Pocket,http://images.amazon.com/images/P/0743457358.0...,http://images.amazon.com/images/P/0743457358.0...,http://images.amazon.com/images/P/0743457358.0...
2033,0671024248,Hearts In Atlantis,Stephen King,2000,Pocket,http://images.amazon.com/images/P/0671024248.0...,http://images.amazon.com/images/P/0671024248.0...,http://images.amazon.com/images/P/0671024248.0...
3828,0451188462,Desperation,Stephen King,1997,Signet Book,http://images.amazon.com/images/P/0451188462.0...,http://images.amazon.com/images/P/0451188462.0...,http://images.amazon.com/images/P/0451188462.0...
5544,0451184963,Insomnia,Stephen King,1995,Signet Book,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...
7858,0451186362,Rose Madder,Stephen King,2004,Signet Book,http://images.amazon.com/images/P/0451186362.0...,http://images.amazon.com/images/P/0451186362.0...,http://images.amazon.com/images/P/0451186362.0...
8292,0345441036,Black House,Stephen King,2002,Ballantine Books,http://images.amazon.com/images/P/0345441036.0...,http://images.amazon.com/images/P/0345441036.0...,http://images.amazon.com/images/P/0345441036.0...
10149,0451180232,Nightmares &amp; Dreamscapes,Stephen King,2004,Signet Book,http://images.amazon.com/images/P/0451180232.0...,http://images.amazon.com/images/P/0451180232.0...,http://images.amazon.com/images/P/0451180232.0...
11103,0451160525,"The Gunslinger (The Dark Tower, Book 1)",Stephen King,1994,New American Library,http://images.amazon.com/images/P/0451160525.0...,http://images.amazon.com/images/P/0451160525.0...,http://images.amazon.com/images/P/0451160525.0...
11884,0425147517,The Key to Midnight,Dean R. Koontz,1995,Berkley Publishing Group,http://images.amazon.com/images/P/0425147517.0...,http://images.amazon.com/images/P/0425147517.0...,http://images.amazon.com/images/P/0425147517.0...
30534,0345444884,The Talisman,STEPHEN KING,2001,Ballantine Books,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...

## Serendipity Similarity

In [28]:
top_ten = book_sets.apply(Serendipity_sim).sort_values(ascending=False).head(10)

In [29]:
Serendipity_ten = good_books[good_books['ISBN'].isin(top_ten.index)]
Serendipity_ten

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1926,0743457358,Everything's Eventual : 14 Dark Tales,Stephen King,2002,Pocket,http://images.amazon.com/images/P/0743457358.0...,http://images.amazon.com/images/P/0743457358.0...,http://images.amazon.com/images/P/0743457358.0...
3828,0451188462,Desperation,Stephen King,1997,Signet Book,http://images.amazon.com/images/P/0451188462.0...,http://images.amazon.com/images/P/0451188462.0...,http://images.amazon.com/images/P/0451188462.0...
5544,0451184963,Insomnia,Stephen King,1995,Signet Book,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...
7858,0451186362,Rose Madder,Stephen King,2004,Signet Book,http://images.amazon.com/images/P/0451186362.0...,http://images.amazon.com/images/P/0451186362.0...,http://images.amazon.com/images/P/0451186362.0...
8292,0345441036,Black House,Stephen King,2002,Ballantine Books,http://images.amazon.com/images/P/0345441036.0...,http://images.amazon.com/images/P/0345441036.0...,http://images.amazon.com/images/P/0345441036.0...
8716,0425132951,The House of Thunder,Dean R. Koontz,1993,Berkley Publishing Group,http://images.amazon.com/images/P/0425132951.0...,http://images.amazon.com/images/P/0425132951.0...,http://images.amazon.com/images/P/0425132951.0...
10149,0451180232,Nightmares &amp; Dreamscapes,Stephen King,2004,Signet Book,http://images.amazon.com/images/P/0451180232.0...,http://images.amazon.com/images/P/0451180232.0...,http://images.amazon.com/images/P/0451180232.0...
11103,0451160525,"The Gunslinger (The Dark Tower, Book 1)",Stephen King,1994,New American Library,http://images.amazon.com/images/P/0451160525.0...,http://images.amazon.com/images/P/0451160525.0...,http://images.amazon.com/images/P/0451160525.0...
11884,0425147517,The Key to Midnight,Dean R. Koontz,1995,Berkley Publishing Group,http://images.amazon.com/images/P/0425147517.0...,http://images.amazon.com/images/P/0425147517.0...,http://images.amazon.com/images/P/0425147517.0...
30534,0345444884,The Talisman,STEPHEN KING,2001,Ballantine Books,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...

## Overlap Similarity

In [30]:
top_ten = book_sets.apply(Overlap_sim).sort_values(ascending=False).head(10)

In [31]:
Overlap_ten = good_books[good_books['ISBN'].isin(top_ten.index)]
Overlap_ten

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
26,0971880107,Wild Animus,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...
305,044023722X,A Painted House,John Grisham,2001,Dell Publishing Company,http://images.amazon.com/images/P/044023722X.0...,http://images.amazon.com/images/P/044023722X.0...,http://images.amazon.com/images/P/044023722X.0...
408,0316666343,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...
748,0385504209,The Da Vinci Code,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...
953,0440211727,A Time to Kill,JOHN GRISHAM,1992,Dell,http://images.amazon.com/images/P/0440211727.0...,http://images.amazon.com/images/P/0440211727.0...,http://images.amazon.com/images/P/0440211727.0...
1105,0060928336,Divine Secrets of the Ya-Ya Sisterhood: A Novel,Rebecca Wells,1997,Perennial,http://images.amazon.com/images/P/0060928336.0...,http://images.amazon.com/images/P/0060928336.0...,http://images.amazon.com/images/P/0060928336.0...
2526,0345337662,Interview with the Vampire,Anne Rice,1993,Ballantine Books,http://images.amazon.com/images/P/0345337662.0...,http://images.amazon.com/images/P/0345337662.0...,http://images.amazon.com/images/P/0345337662.0...
5544,0451184963,Insomnia,Stephen King,1995,Signet Book,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...
30534,0345444884,The Talisman,STEPHEN KING,2001,Ballantine Books,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...

## Correlation Similarity

In [35]:
top_ten = ratings_matrix.apply(correlation_sim).sort_values(ascending=False).head(10)

In [36]:
Correlation_ten = good_books[good_books['ISBN'].isin(top_ten.index)]
Correlation_ten

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
881,0743211383,Dreamcatcher,Stephen King,2001,Scribner,http://images.amazon.com/images/P/0743211383.0...,http://images.amazon.com/images/P/0743211383.0...,http://images.amazon.com/images/P/0743211383.0...
2941,0345384369,Intensity,DEAN KOONTZ,1996,Ballantine Books,http://images.amazon.com/images/P/0345384369.0...,http://images.amazon.com/images/P/0345384369.0...,http://images.amazon.com/images/P/0345384369.0...
3233,0375412824,The Dive From Clausen's Pier (Alex Awards),ANN PACKER,2002,Knopf,http://images.amazon.com/images/P/0375412824.0...,http://images.amazon.com/images/P/0375412824.0...,http://images.amazon.com/images/P/0375412824.0...
5544,0451184963,Insomnia,Stephen King,1995,Signet Book,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...
5593,0425170349,Rainbow Six,Tom Clancy,2004,Berkley Publishing Group,http://images.amazon.com/images/P/0425170349.0...,http://images.amazon.com/images/P/0425170349.0...,http://images.amazon.com/images/P/0425170349.0...
7858,0451186362,Rose Madder,Stephen King,2004,Signet Book,http://images.amazon.com/images/P/0451186362.0...,http://images.amazon.com/images/P/0451186362.0...,http://images.amazon.com/images/P/0451186362.0...
10149,0451180232,Nightmares &amp; Dreamscapes,Stephen King,2004,Signet Book,http://images.amazon.com/images/P/0451180232.0...,http://images.amazon.com/images/P/0451180232.0...,http://images.amazon.com/images/P/0451180232.0...
10917,0312974256,Welcome to Temptation,Jennifer Crusie,2001,St. Martin's Paperbacks,http://images.amazon.com/images/P/0312974256.0...,http://images.amazon.com/images/P/0312974256.0...,http://images.amazon.com/images/P/0312974256.0...
13188,0449203794,Space,James A. Michener,1988,Fawcett Books,http://images.amazon.com/images/P/0449203794.0...,http://images.amazon.com/images/P/0449203794.0...,http://images.amazon.com/images/P/0449203794.0...
30534,0345444884,The Talisman,STEPHEN KING,2001,Ballantine Books,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...

## Cosine Similarity

In [33]:
top_ten = ratings_matrix.apply(cosine_sim).sort_values(ascending=False).head(10)

In [34]:
Cosine_ten = good_books[good_books['ISBN'].isin(top_ten.index)]
Cosine_ten

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
28,0345417623,Timeline,MICHAEL CRICHTON,2000,Ballantine Books,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...
881,0743211383,Dreamcatcher,Stephen King,2001,Scribner,http://images.amazon.com/images/P/0743211383.0...,http://images.amazon.com/images/P/0743211383.0...,http://images.amazon.com/images/P/0743211383.0...
2037,0451151259,Eyes of the Dragon,Stephen King,1988,Penguin Putnam~mass,http://images.amazon.com/images/P/0451151259.0...,http://images.amazon.com/images/P/0451151259.0...,http://images.amazon.com/images/P/0451151259.0...
2911,0451153553,Misery,Stephen King,1988,New Amer Library,http://images.amazon.com/images/P/0451153553.0...,http://images.amazon.com/images/P/0451153553.0...,http://images.amazon.com/images/P/0451153553.0...
5544,0451184963,Insomnia,Stephen King,1995,Signet Book,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...,http://images.amazon.com/images/P/0451184963.0...
5554,0451156609,The Tommyknockers,Stephen King,1994,Signet Book,http://images.amazon.com/images/P/0451156609.0...,http://images.amazon.com/images/P/0451156609.0...,http://images.amazon.com/images/P/0451156609.0...
8784,0345413881,Dr. Death (Alex Delaware Novels (Paperback)),Jonathan Kellerman,2001,Ballantine Books,http://images.amazon.com/images/P/0345413881.0...,http://images.amazon.com/images/P/0345413881.0...,http://images.amazon.com/images/P/0345413881.0...
10149,0451180232,Nightmares &amp; Dreamscapes,Stephen King,2004,Signet Book,http://images.amazon.com/images/P/0451180232.0...,http://images.amazon.com/images/P/0451180232.0...,http://images.amazon.com/images/P/0451180232.0...
13188,0449203794,Space,James A. Michener,1988,Fawcett Books,http://images.amazon.com/images/P/0449203794.0...,http://images.amazon.com/images/P/0449203794.0...,http://images.amazon.com/images/P/0449203794.0...
30534,0345444884,The Talisman,STEPHEN KING,2001,Ballantine Books,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...,http://images.amazon.com/images/P/0345444884.0...