# Map, Apply, and Applymap

In [1]:
import pandas as pd
import numpy as np

## The map method

In [7]:
# load the Titanic dataset

url = 'https://raw.githubusercontent.com/um-perez-alvaro/Data-Science-Practice/master/Data/titanic.csv'

titanic = pd.read_csv(url)

In [8]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
# we are going female to 1 and male to 0
map_dic = {'female':1, 'male':0}
titanic.Sex.map(map_dic)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: int64

In [10]:
# the same, but using a function instead of a dictionary (probably more what this  is for)

def map_func(sex):
    if sex=='female':
        return 1
    else:
        return 0

In [12]:
titanic.Sex.map(map_func)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: int64

## The apply method (with a series)

Example 1: find the length of the strings in the Name column

In [15]:
# python len(lengths)
len('Javier')

6

In [17]:
titanic['Name Length'] = titanic.Name.apply(len)

In [19]:
titanic[['Name','Name Length']]

                                                  Name  Name Length
0                              Braund, Mr. Owen Harris           23
1    Cumings, Mrs. John Bradley (Florence Briggs Th...           51
2                               Heikkinen, Miss. Laina           22
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)           44
4                             Allen, Mr. William Henry           24
..                                                 ...          ...
886                              Montvila, Rev. Juozas           21
887                       Graham, Miss. Margaret Edith           28
888           Johnston, Miss. Catherine Helen "Carrie"           40
889                              Behr, Mr. Karl Howell           21
890                                Dooley, Mr. Patrick           19

[891 rows x 2 columns]

In [20]:
# you can also use map here:

titanic.Name.map(len)

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

Example 2: extract the last name of each passenger

In [22]:
titanic.Name[0].split(',')[0]

'Braund'

In [23]:
def get_last_name(name):
    return name.split(',')[0]

In [24]:
titanic.Name.apply(get_last_name)

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Name, Length: 891, dtype: object

In [25]:
# using a lambda function
titanic.Name.apply(lambda name:name.split(',')[0])

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Name, Length: 891, dtype: object

## The apply method (with a dataframe)

In [45]:
# load the alcohol consumption data
url1='https://raw.githubusercontent.com/um-perez-alvaro/Data-Science-Practice/master/Data/drinks.csv'
drinks = pd.read_csv(url1)
drinks.set_index('country',inplace=True)

In [46]:
drinks.drop('continent',axis=1,inplace=True)

Example 1: find the maximum value in each column

In [47]:
drinks.apply(np.max,axis=0) #axis=0 means we apply along the rows

beer_servings                   376.0
spirit_servings                 438.0
wine_servings                   370.0
total_litres_of_pure_alcohol     14.4
dtype: float64

In [48]:
# alternatively, use pandas built in function
drinks.max()

beer_servings                   376.0
spirit_servings                 438.0
wine_servings                   370.0
total_litres_of_pure_alcohol     14.4
dtype: float64

Example 2: find the max value in each row

In [52]:
drinks.apply(np.max,axis=1)

country
Afghanistan      0.0
Albania        132.0
Algeria         25.0
Andorra        312.0
Angola         217.0
               ...
Venezuela      333.0
Vietnam        111.0
Yemen            6.0
Zambia          32.0
Zimbabwe        64.0
Length: 193, dtype: float64

In [54]:
drinks.max(axis=1)['USA']  # is this about wine, beer, or spirits?

249.0

Example 3: Find the column that has the maximum value

In [56]:
drinks.apply(np.argmax,axis=1).map({0:'beer',1:'wine',2:'spirits',3:'pure alcohol'})

country
Afghanistan       beer
Albania           wine
Algeria           beer
Andorra        spirits
Angola            beer
                ...
Venezuela         beer
Vietnam           beer
Yemen             beer
Zambia            beer
Zimbabwe          beer
Length: 193, dtype: object

In [57]:
drinks.apply(np.argmax,axis=1).map({0:'beer',1:'wine',2:'spirits',3:'pure alcohol'})[['USA','Spain']]

country
USA      beer
Spain    beer
dtype: object

## The applymap method

In [58]:
# transform everything into strings

silly_df = drinks.applymap(str)

In [60]:
silly_df.iloc[0,0]

'0'

In [61]:
drinks.iloc[0,0]

0