In [1]:
import pandas as pd

# Practice problem II

In [2]:
# load the Alcohol consumption by country dataset
url = 'https://raw.githubusercontent.com/um-perez-alvaro/Data-Science-Practice/master/Data/drinks.csv'
drinks = pd.read_csv(url, index_col='country')

Display the first 10 entries of the dataset

In [3]:
drinks.head(10)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
Antigua & Barbuda,102,128,45,4.9,North America
Argentina,193,25,221,8.3,South America
Armenia,21,179,11,3.8,Europe
Australia,261,72,212,10.4,Oceania
Austria,279,75,191,9.7,Europe

What is the number of observations (rows) in the dataset?

In [4]:
len(drinks)

193

What is the number of columns in the dataset?

In [6]:
drinks.shape[1]

5

Print the name of all the columns.

In [12]:
print(drinks.columns)

Index(['beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

print data for Albania (using loc)

In [13]:
drinks.loc[['Albania'],:]

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Albania,89,132,54,4.9,Europe

print data for USA and Spain (using loc)

In [14]:
drinks.loc[['USA', 'Spain'],:]

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
USA,249,158,84,8.7,North America
Spain,284,157,112,10.0,Europe

drop the 'continent' column

In [16]:
drinks.drop(['continent'], axis=1, inplace=True)

drop the row corresponding to Angola

In [29]:
drinks.drop(['Angola'], axis=0, inplace=True)

In [30]:
drinks.head(10)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
country,,,,
Afghanistan,0,0,0,0.0
Albania,89,132,54,4.9
Algeria,25,0,14,0.7
Andorra,245,138,312,12.4
Antigua & Barbuda,102,128,45,4.9
Argentina,193,25,221,8.3
Armenia,21,179,11,3.8
Australia,261,72,212,10.4
Austria,279,75,191,9.7
Azerbaijan,21,46,5,1.3

Print out wine_servings data for France

In [37]:
drinks.loc['France', 'wine_servings']

370

In [38]:
#verify
drinks.loc['France', :]

beer_servings                   127.0
spirit_servings                 151.0
wine_servings                   370.0
total_litres_of_pure_alcohol     11.8
Name: France, dtype: float64

Print out total_litres_of_pure_alcohol column three different ways

In [39]:
drinks['total_litres_of_pure_alcohol']

country
Afghanistan           0.0
Albania               4.9
Algeria               0.7
Andorra              12.4
Antigua & Barbuda     4.9
                     ...
Venezuela             7.7
Vietnam               2.0
Yemen                 0.1
Zambia                2.5
Zimbabwe              4.7
Name: total_litres_of_pure_alcohol, Length: 192, dtype: float64

In [40]:
drinks.total_litres_of_pure_alcohol

country
Afghanistan           0.0
Albania               4.9
Algeria               0.7
Andorra              12.4
Antigua & Barbuda     4.9
                     ...
Venezuela             7.7
Vietnam               2.0
Yemen                 0.1
Zambia                2.5
Zimbabwe              4.7
Name: total_litres_of_pure_alcohol, Length: 192, dtype: float64

In [41]:
drinks.loc[:,'total_litres_of_pure_alcohol']

country
Afghanistan           0.0
Albania               4.9
Algeria               0.7
Andorra              12.4
Antigua & Barbuda     4.9
                     ...
Venezuela             7.7
Vietnam               2.0
Yemen                 0.1
Zambia                2.5
Zimbabwe              4.7
Name: total_litres_of_pure_alcohol, Length: 192, dtype: float64