In [2]:
import pandas as pd

In [3]:
# read the UFO data
url = 'https://raw.githubusercontent.com/um-perez-alvaro/Data-Science-Practice/master/Data/ufo.csv'
ufo = pd.read_csv(url)

In [6]:
ufo.head(10) # first ten rows

                   City Colors Reported Shape Reported State              Time
0                Ithaca             NaN       TRIANGLE    NY    6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ   6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO   2/15/1931 14:00
3               Abilene             NaN           DISK    KS    6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY   4/18/1933 19:00
5           Valley City             NaN           DISK    ND   9/15/1934 15:30
6           Crater Lake             NaN         CIRCLE    CA    6/15/1935 0:00
7                  Alma             NaN           DISK    MI    7/15/1936 0:00
8               Eklutna             NaN          CIGAR    AK  10/15/1936 17:00
9               Hubbard             NaN       CYLINDER    OR    6/15/1937 0:00

In [7]:
ufo.tail(10) # last ten rows

                 City Colors Reported Shape Reported State              Time
18231     Pismo Beach             NaN           OVAL    CA  12/31/2000 20:00
18232            Lodi             NaN            NaN    WI  12/31/2000 20:30
18233       Anchorage             RED        VARIOUS    AK  12/31/2000 21:00
18234        Capitola             NaN       TRIANGLE    CA  12/31/2000 22:00
18235  Fountain Hills             NaN            NaN    AZ  12/31/2000 23:00
18236      Grant Park             NaN       TRIANGLE    IL  12/31/2000 23:00
18237     Spirit Lake             NaN           DISK    IA  12/31/2000 23:00
18238     Eagle River             NaN            NaN    WI  12/31/2000 23:45
18239     Eagle River             RED          LIGHT    WI  12/31/2000 23:45
18240            Ybor             NaN           OVAL    FL  12/31/2000 23:59

In [8]:
len(ufo) # number of rows

18241

In [9]:
# get size of the dataframe: rows x columns
ufo.shape

(18241, 5)

In [10]:
# dataframe columns
ufo.columns

Index(['City', 'Colors Reported', 'Shape Reported', 'State', 'Time'], dtype='object')

In [12]:
# datatypes of columns
ufo.dtypes

City               object
Colors Reported    object
Shape Reported     object
State              object
Time               object
dtype: object

In [13]:
# bracket notation
ufo['City']

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
                 ...
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: object

In [14]:
ufo.City

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
                 ...
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: object

In [15]:
# set Time column as index
ufo.set_index('Time', 
                 inplace=True)
#inplace=True means what?

In [16]:
# create new Location column
ufo['Location'] = ufo.City + ', ' + ufo.State

In [19]:
#  Rename the 'Colors Reported' and 'Shape Reported' columns to 'colors_reported' and 'shape_reported'

# create a dictionary with the new names
new_column_names = {'Colors Reported':'colors_reported', 'Shape Reported':'shape_reported'}

# rename columns
ufo.rename(columns=new_column_names, inplace=True)
ufo.head()

,City,colors_reported,shape_reported,State,Location
Time,,,,,
6/1/1930 22:00,Ithaca,NaN,TRIANGLE,NY,"Ithaca, NY"
6/30/1930 20:00,Willingboro,NaN,OTHER,NJ,"Willingboro, NJ"
2/15/1931 14:00,Holyoke,NaN,OVAL,CO,"Holyoke, CO"
6/1/1931 13:00,Abilene,NaN,DISK,KS,"Abilene, KS"
4/18/1933 19:00,New York Worlds Fair,NaN,LIGHT,NY,"New York Worlds Fair, NY"

In [20]:
# Remove the 'colors_reported' column

ufo.drop('colors_reported', axis=1, inplace=True)

In [24]:
# Remove rows 0 and 1



ufo.reset_index(inplace=True,
                   drop=False)

ufo.drop([0,1], axis=0, inplace=True)

In [26]:
ufo.head()

,Time,City,shape_reported,State,Location
2,2/15/1931 14:00,Holyoke,OVAL,CO,"Holyoke, CO"
3,6/1/1931 13:00,Abilene,DISK,KS,"Abilene, KS"
4,4/18/1933 19:00,New York Worlds Fair,LIGHT,NY,"New York Worlds Fair, NY"
5,9/15/1934 15:30,Valley City,DISK,ND,"Valley City, ND"
6,6/15/1935 0:00,Crater Lake,CIRCLE,CA,"Crater Lake, CA"